### ISSUE TITLE
Does not work with pg11

### ISSUE THREAD

**Issue by kodeine** [timescale/helm-charts#493]
```
  image:
    # Image was built from
    # https://github.com/timescale/timescaledb-docker-ha
    repository: timescale/timescaledb-ha
    tag: pg11-latest
    pullPolicy: IfNotPresent

  env:
  - name: POSTGIS_VERSIONS
    value: "2.5.5"
  - name: PG_VERSIONS
    value: "11"
  - name: PG_MAJOR
    value: "11"
```

```
    return getattr(self._core_v1_api, func)(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 402, in wrapper
    return self._api_client.call_api(method, path, headers, body, **kwargs)
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 371, in call_api
    return self._handle_server_response(response, _preload_content)
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 201, in _handle_server_response
    raise k8s_client.rest.ApiException(http_resp=response)
patroni.dcs.kubernetes.K8sClient.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '62280206-7b0b-4d11-8914-da3a5c26d7c5', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': 'c3fa255c-dbbe-4be1-b3d2-8534241f0b48', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'b2bd8c25-0d40-4b30-90f3-239d522d9f6d', 'Date': 'Wed, 16 Nov 2022 01:45:18 GMT', 'Content-Length': '308'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services is forbidden: User \\"system:serviceaccount:timescaledb:timescaledb\\" cannot create resource \\"services\\" in API group \\"\\" in the namespace \\"timescaledb\\"","reason":"Forbidden","details":{"kind":"services"},"code":403}\n'

2022-11-16 01:45:18,089 WARNING: max_wal_senders setting is missing from pg_controldata output
2022-11-16 01:45:19.166 GMT [1486] LOG:  unrecognized configuration parameter "wal_keep_size" in file "/var/lib/postgresql/data/postgresql.conf" line 42
2022-11-16 01:45:19.172 GMT [1486] LOG:  unrecognized configuration parameter "recovery_target" in file "/var/lib/postgresql/data/postgresql.conf" line 49
2022-11-16 01:45:19.172 GMT [1486] LOG:  unrecognized configuration parameter "recovery_target_lsn" in file "/var/lib/postgresql/data/postgresql.conf" line 50
2022-11-16 01:45:19.172 GMT [1486] LOG:  unrecognized configuration parameter "recovery_target_name" in file "/var/lib/postgresql/data/postgresql.conf" line 51
2022-11-16 01:45:19.172 GMT [1486] LOG:  unrecognized configuration parameter "recovery_target_time" in file "/var/lib/postgresql/data/postgresql.conf" line 52
2022-11-16 01:45:19.172 GMT [1486] LOG:  unrecognized configuration parameter "recovery_target_timeline" in file "/var/lib/postgresql/data/postgresql.conf" line 53
2022-11-16 01:45:19.172 GMT [1486] LOG:  unrecognized configuration parameter "recovery_target_xid" in file "/var/lib/postgresql/data/postgresql.conf" line 54
2022-11-16 01:45:19.172 GMT [1486] LOG:  unrecognized configuration parameter "restore_command" in file "/var/lib/postgresql/data/postgresql.conf" line 55
2022-11-16 01:45:19.172 GMT [1486] FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
/var/run/postgresql:5432 - no response
2022-11-16 01:45:19,275 WARNING: Postgresql is not running.
2022-11-16 01:45:19,392 ERROR: create_config_service failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 877, in _create_config_service
    if not self._api.create_namespaced_service(self._namespace, body):
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 466, in wrapper
    return getattr(self._core_v1_api, func)(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 402, in wrapper
    return self._api_client.call_api(method, path, headers, body, **kwargs)
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 371, in call_api
    return self._handle_server_response(response, _preload_content)
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 201, in _handle_server_response
    raise k8s_client.rest.ApiException(http_resp=response)
patroni.dcs.kubernetes.K8sClient.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '0fdc5f9b-fae7-4638-9cad-1b8b27420c7e', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': 'c3fa255c-dbbe-4be1-b3d2-8534241f0b48', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'b2bd8c25-0d40-4b30-90f3-239d522d9f6d', 'Date': 'Wed, 16 Nov 2022 01:45:19 GMT', 'Content-Length': '308'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services is forbidden: User \\"system:serviceaccount:timescaledb:timescaledb\\" cannot create resource \\"services\\" in API group \\"\\" in the namespace \\"timescaledb\\"","reason":"Forbidden","details":{"kind":"services"},"code":403}\n'

2022-11-16 01:45:19,409 WARNING: max_wal_senders setting is missing from pg_controldata output
2022-11-16 01:45:20.327 GMT [1496] LOG:  unrecognized configuration parameter "wal_keep_size" in file "/var/lib/postgresql/data/postgresql.conf" line 42
2022-11-16 01:45:20.327 GMT [1496] LOG:  unrecognized configuration parameter "recovery_target" in file "/var/lib/postgresql/data/postgresql.conf" line 49
2022-11-16 01:45:20.327 GMT [1496] LOG:  unrecognized configuration parameter "recovery_target_lsn" in file "/var/lib/postgresql/data/postgresql.conf" line 50
2022-11-16 01:45:20.327 GMT [1496] LOG:  unrecognized configuration parameter "recovery_target_name" in file "/var/lib/postgresql/data/postgresql.conf" line 51
2022-11-16 01:45:20.327 GMT [1496] LOG:  unrecognized configuration parameter "recovery_target_time" in file "/var/lib/postgresql/data/postgresql.conf" line 52
2022-11-16 01:45:20.327 GMT [1496] LOG:  unrecognized configuration parameter "recovery_target_timeline" in file "/var/lib/postgresql/data/postgresql.conf" line 53
2022-11-16 01:45:20.327 GMT [1496] LOG:  unrecognized configuration parameter "recovery_target_xid" in file "/var/lib/postgresql/data/postgresql.conf" line 54
2022-11-16 01:45:20.327 GMT [1496] LOG:  unrecognized configuration parameter "restore_command" in file "/var/lib/postgresql/data/postgresql.conf" line 55
2022-11-16 01:45:20.327 GMT [1496] FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
/var/run/postgresql:5432 - no response
2022-11-16 01:45:20,449 WARNING: Postgresql is not running.
2022-11-16 01:45:20,548 ERROR: create_config_service failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 877, in _create_config_service
    if not self._api.create_namespaced_service(self._namespace, body):
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 466, in wrapper
    return getattr(self._core_v1_api, func)(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 402, in wrapper
    return self._api_client.call_api(method, path, headers, body, **kwargs)
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 371, in call_api
    return self._handle_server_response(response, _preload_content)
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 201, in _handle_server_response
    raise k8s_client.rest.ApiException(http_resp=response)
patroni.dcs.kubernetes.K8sClient.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '8b616df4-a2db-4775-8bfa-ad6ea7d6ab1c', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': 'c3fa255c-dbbe-4be1-b3d2-8534241f0b48', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'b2bd8c25-0d40-4b30-90f3-239d522d9f6d', 'Date': 'Wed, 16 Nov 2022 01:45:20 GMT', 'Content-Length': '308'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services is forbidden: User \\"system:serviceaccount:timescaledb:timescaledb\\" cannot create resource \\"services\\" in API group \\"\\" in the namespace \\"timescaledb\\"","reason":"Forbidden","details":{"kind":"services"},"code":403}\n'

2022-11-16 01:45:20,580 WARNING: max_wal_senders setting is missing from pg_controldata output
2022-11-16 01:45:21.190 GMT [1506] LOG:  unrecognized configuration parameter "wal_keep_size" in file "/var/lib/postgresql/data/postgresql.conf" line 42
2022-11-16 01:45:21.190 GMT [1506] LOG:  unrecognized configuration parameter "recovery_target" in file "/var/lib/postgresql/data/postgresql.conf" line 49
2022-11-16 01:45:21.190 GMT [1506] LOG:  unrecognized configuration parameter "recovery_target_lsn" in file "/var/lib/postgresql/data/postgresql.conf" line 50
2022-11-16 01:45:21.190 GMT [1506] LOG:  unrecognized configuration parameter "recovery_target_name" in file "/var/lib/postgresql/data/postgresql.conf" line 51
2022-11-16 01:45:21.192 GMT [1506] LOG:  unrecognized configuration parameter "recovery_target_time" in file "/var/lib/postgresql/data/postgresql.conf" line 52
2022-11-16 01:45:21.192 GMT [1506] LOG:  unrecognized configuration parameter "recovery_target_timeline" in file "/var/lib/postgresql/data/postgresql.conf" line 53
2022-11-16 01:45:21.192 GMT [1506] LOG:  unrecognized configuration parameter "recovery_target_xid" in file "/var/lib/postgresql/data/postgresql.conf" line 54
2022-11-16 01:45:21.192 GMT [1506] LOG:  unrecognized configuration parameter "restore_command" in file "/var/lib/postgresql/data/postgresql.conf" line 55
2022-11-16 01:45:21.192 GMT [1506] FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
2022-11-16 01:45:21,259 ERROR: postmaster is not running
2022-11-16 01:45:21,264 WARNING: Postgresql is not running.
2022-11-16 01:45:21,324 ERROR: create_config_service failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 877, in _create_config_service
    if not self._api.create_namespaced_service(self._namespace, body):
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 466, in wrapper
    return getattr(self._core_v1_api, func)(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 402, in wrapper
    return self._api_client.call_api(method, path, headers, body, **kwargs)
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 371, in call_api
    return self._handle_server_response(response, _preload_content)
  File "/usr/lib/python3/dist-packages/patroni/dcs/kubernetes.py", line 201, in _handle_server_response
    raise k8s_client.rest.ApiException(http_resp=response)
patroni.dcs.kubernetes.K8sClient.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '5ce9313d-98f7-43f3-9a19-817c2a5f7096', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': 'c3fa255c-dbbe-4be1-b3d2-8534241f0b48', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'b2bd8c25-0d40-4b30-90f3-239d522d9f6d', 'Date': 'Wed, 16 Nov 2022 01:45:21 GMT', 'Content-Length': '308'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services is forbidden: User \\"system:serviceaccount:timescaledb:timescaledb\\" cannot create resource \\"services\\" in API group \\"\\" in the namespace \\"timescaledb\\"","reason":"Forbidden","details":{"kind":"services"},"code":403}\n'

2022-11-16 01:45:21,341 WARNING: max_wal_senders setting is missing from pg_controldata output
```

**Comment by paulfantom** [comment]
postgres 11 is no longer supported
