### ISSUE TITLE
Unrecognized option '--comand=/etc/timescaledb/scripts/restore_or_initdb.sh'

### ISSUE THREAD

**Issue by artursmolarek** [timescale/helm-charts#634]
**What happened?**

While upgrading our stack, we encountered an issue with upgrading from `pg14.9-ts2.12.2` to `pg14.10-ts2.13.0`:

```
2023-12-08 12:03:09 - restore_or_initdb - Invoking initdb
initdb: unrecognized option '--command=/etc/timescaledb/scripts/restore_or_initdb.sh'
Try "initdb --help" for more information.
/var/run/postgresql:5432 - no response
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/patroni/__main__.py", line 239, in patroni_main
    abstract_main(Patroni, configfile)
  File "/usr/lib/python3/dist-packages/patroni/daemon.py", line 174, in abstract_main
    controller.run()
  File "/usr/lib/python3/dist-packages/patroni/__main__.py", line 194, in run
    super(Patroni, self).run()
  File "/usr/lib/python3/dist-packages/patroni/daemon.py", line 143, in run
    self._run_cycle()
  File "/usr/lib/python3/dist-packages/patroni/__main__.py", line 203, in _run_cycle
    logger.info(self.ha.run_cycle())
  File "/usr/lib/python3/dist-packages/patroni/ha.py", line 1972, in run_cycle
    info = self._run_cycle()
  File "/usr/lib/python3/dist-packages/patroni/ha.py", line 1785, in _run_cycle
    return self.post_bootstrap()
  File "/usr/lib/python3/dist-packages/patroni/ha.py", line 1669, in post_bootstrap
    self.cancel_initialization()
  File "/usr/lib/python3/dist-packages/patroni/ha.py", line 1662, in cancel_initialization
    raise PatroniFatalException('Failed to bootstrap cluster')
patroni.exceptions.PatroniFatalException: Failed to bootstrap cluster
```

**Did you expect to see something different?**

We anticipate that the pod containing TimescaleDB will initiate without any problems.

**How to reproduce it (as minimally and precisely as possible)**:

Set:

`tag: pg14.10-ts2.13.0`

in the [timescaledb-single](https://github.com/timescale/helm-charts/tree/main/charts/timescaledb-single) Helm chart.

**Environment**

* Which helm chart and what version are you using?

[timescaledb-single](https://github.com/timescale/helm-charts/tree/main/charts/timescaledb-single) 0.33.1

* What is in your `values.yaml` ?

All values can be found here:

https://github.com/cloudentity/acp-on-k8s/blob/main/infrastructure/timescaledb/base/release.yaml#L18

* Kubernetes version information:

`1.27.3`

* Kubernetes cluster kind:

Kind

**Comment by timhaak** [comment]
The problem started with the images updated on Nov 29, 2023.

Assuming something has changed with the base build and helm charts either need to be updated or have a problem with the build?

For anyone else stuck with this. 

You can deploy with an older version, then update and re-deploy. (Nov 5, 2023 images seem ok)

I got it working by deploying pg15-ts2.12-all and then updating to pg15-all. 

I use the timescaledev/timescaledb-ha image because it has an arm build.

So, the dates and version may be different for the default image. 

However, I don't know if these charts are maintained anymore. (See https://github.com/timescale/helm-charts/issues/596)

**Comment by david-mtrade** [comment]
We are facing the same problem while trying to install `pg15-ts2.12-all`

Our workaround was to install `pg15-ts2.13-all`
